using System;

namespace LabOfKiwi.Html;

public enum PseudoClass
{
    Active,
    AnyLink,
    Autofill,
    Checked,
    Default,
    Defined,
    Disabled,
    Empty,
    Enabled,
    First,
    FirstChild,
    FirstOfType,
    Focus,
    FocusVisible,
    FocusWithin,
    Fullscreen,
    Host,
    Hover,
    InRange,
    Indeterminate,
    Invalid,
    LastChild,
    LastOfType,
    Left,
    Link,
    OnlyChild,
    OnlyOfType,
    Optional,
    OutOfRange,
    Paused,
    PictureInPicture,
    PlaceholderShown,
    Playing,
    ReadOnly,
    ReadWrite,
    Required,
    Right,
    Root,
    Scope,
    Target,
    UserInvalid,
    UseValid,
    Valid,
    Visited
}

internal static class PseudoClassExtensions
{
    public static string ToWebString(this PseudoClass value) => value switch
    {
        PseudoClass.Active => "active",
        PseudoClass.AnyLink => "any-link",
        PseudoClass.Autofill => "autofill",
        PseudoClass.Checked => "checked",
        PseudoClass.Default => "default",
        PseudoClass.Defined => "defined",
        PseudoClass.Disabled => "disabled",
        PseudoClass.Empty => "empty",
        PseudoClass.Enabled => "enabled",
        PseudoClass.First => "first",
        PseudoClass.FirstChild => "first-child",
        PseudoClass.FirstOfType => "first-of-type",
        PseudoClass.Focus => "focus",
        PseudoClass.FocusVisible => "focus-visible",
        PseudoClass.FocusWithin => "focus-within",
        PseudoClass.Fullscreen => "fullscreen",
        PseudoClass.Host => "host",
        PseudoClass.Hover => "hover",
        PseudoClass.InRange => "in-range",
        PseudoClass.Indeterminate => "indeterminate",
        PseudoClass.Invalid => "invalid",
        PseudoClass.LastChild => "last-child",
        PseudoClass.LastOfType => "last-of-type",
        PseudoClass.Left => "left",
        PseudoClass.Link => "link",
        PseudoClass.OnlyChild => "only-child",
        PseudoClass.OnlyOfType => "only-of-type",
        PseudoClass.Optional => "optional",
        PseudoClass.OutOfRange => "out-of-range",
        PseudoClass.Paused => "paused",
        PseudoClass.PictureInPicture => "picture-in-picture",
        PseudoClass.PlaceholderShown => "placeholder-shown",
        PseudoClass.Playing => "playing",
        PseudoClass.ReadOnly => "read-only",
        PseudoClass.ReadWrite => "read-write",
        PseudoClass.Required => "required",
        PseudoClass.Right => "right",
        PseudoClass.Root => "root",
        PseudoClass.Scope => "scope",
        PseudoClass.Target => "target",
        PseudoClass.UserInvalid => "user-invalid",
        PseudoClass.UseValid => "use-valid",
        PseudoClass.Valid => "valid",
        PseudoClass.Visited => "visited",
        _ => throw new NotImplementedException(),
    };
}
